/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.HashMultiset;
import com.google.common.collect.Multiset;

import java.util.List;


/**
 * To start the application:
 * ./gradlew build
 * java -jar ./hw01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l hw01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 */
public class HelloOtus {
    public static void main(String... args) {
        Multiset<String> words = HashMultiset.create();
        words.addAll(List.of("hello", "hello", "hello"));
        for (String word : words) {
            System.out.printf("%s ! ", word.toUpperCase());
        }
    }
}